// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://allfnbgpbbsbucfczzbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsbGZuYmdwYmJzYnVjZmN6emJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTQyMzEsImV4cCI6MjA2MTU5MDIzMX0.T0QzsirNkqcf9G26P4I_t-qlSw3GalZv9Tu7UtVASvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
