// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkqvwmnvjjfszmfeltoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrcXZ3bW52ampmc3ptZmVsdG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzIyNTIsImV4cCI6MjA2MTQwODI1Mn0._QD3kJZ2R9ZhcGWer9ZWT6Why4qDnP21mAxBCCslKaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);